config/routes.rb
Rails.application.routes.draw do
  root 'tasks#index'
  resources :tasks 
  resources :users, only:[ :new, :create, :show ]
    namespace :admin do
      resources :users
    end
  resources :sessions, only: [:new, :create, :destroy]
  resources :labels
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/label.rb
class Label < ApplicationRecord
  has_many :labelings, dependent: :destroy
  belongs_to :user
end

app/models/labeling.rb
class Labeling < ApplicationRecord
  belongs_to :task
  belongs_to :label
end

app/models/task.rb
class Task < ApplicationRecord
  validates :task_title, presence: true
  validates :task_content, presence: true
  belongs_to :user
  has_many :labelings, dependent: :destroy
  has_many :labels, through: :labelings

  enum status: { 未着手:1, 着手中:2, 完了:3 }
  enum priority: { 低:1, 中:2, 高:3 }
  
  scope :search, -> (search_params) do
    return if search_params.blank?
    search_title(search_params[:task_title])
      .search_status(search_params[:status])
      .search_label(search_params[:label_id])
  end

  scope :search_title, -> (task_title) {where("task_title LIKE ?", "%#{task_title}%") if task_title.present?}
  scope :search_status, -> (status) {where(status: status) if status.present?}
  scope :search_label, -> (label_id) {where(labels: label_id ) if label_id.present?}
end

app/models/user.rb
class User < ApplicationRecord
  before_update :admin_cannot_update
  before_destroy :admin_cannot_delete

  validates :name, presence: true
  validates :email, presence: true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  has_secure_password
  validates :password, length: { minimum: 6 }, on: :new
  has_many :tasks, dependent: :destroy
  has_many :labels, dependent: :destroy


  private

  def admin_cannot_update
    @admin_user = User.where(admin: true)
    throw :abort if @admin_user.count == 1 && @admin_user.first == self && self.admin == false
  end

  def admin_cannot_delete
    throw :abort if User.where(admin: true).count == 1 && self.admin
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :if_not_admin
  
  def index
    @users = User.select(:id, :name, :email, :admin ).order(created_at: :asc)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_users_path
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_users_path, notice:'ユーザー情報を編集しました！'
    else
      flash.now[:notice] = "管理者権限を所有する人がいなくなるため更新できません"
      render :edit
    end
  end


  def destroy
    @user = User.find(params[:id])
    if @user.destroy 
      redirect_to admin_users_path, notice:'ユーザー情報に関するデータを全て削除しました' 
    else
      flash.now[:notice] = "管理者がいなくなるため削除できませんでした。"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :admin)
  end

  def if_not_admin
    redirect_to root_path, notice:'管理者のみがアクセスできます' unless current_user.admin?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  before_action :login_required

  def login_required
    redirect_to new_session_path unless current_user
  end

end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController

  def index
    @labels = Label.all
  end

  def new
    @label = Label.new
  end

  def create
    @label = current_user.labels.build(params_label)
      if @label.save
        redirect_to labels_path, notice: '作成しました！'
      else
        render :new
      end
  end

  def edit
    @label = Label.find(params[:id])
  end

  def update
    @label = Label.find(params[:id])
    if @label.update(params_label)
      redirect_to labels_path, notice: '更新しました！'
    else
      render :edit
    end
  end

  def destroy
    @label = Label.find(params[:id])
    @label.destroy
    redirect_to labels_path
  end

  private
  def params_label
    params.require(:label).permit(:label_name)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only:[ :new, :create ]

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(current_user.id), notice: 'ログインしました！'
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :check_user, only: %i[ edit update destroy]


  def index
    @tasks = current_user.tasks.order(created_at: :desc)
    #終了期限で降順にする場合↓
    @tasks = @tasks.reorder(deadline: :asc) if params[:sort_expired]
    #優先順位で降順にする場合↓
    @tasks = @tasks.reorder(priority: :desc) if params[:sort_priority]
    #タイトルのあいまい検索,ステータス検索,ラベル検索
    @search_params = task_search_params
    @tasks = @tasks.joins(:labels).search(@search_params) if params[:search].present?
    #kaminari gem
    @tasks = @tasks.page(params[:page])
  end

  def new
    @task = Task.new
  end

  def create
    @task = current_user.tasks.build(task_params)
    if @task.save
      redirect_to task_path(@task), notice: "タスクを作成しました！"
    else
      render :new
    end
  end

  def show
    @task = Task.find(params[:id])
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    if @task.update(task_params)
      redirect_to task_path(params[:id]), notice: "タスクを編集しました！"
    else
      render :edit
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    if current_user.admin == true
      redirect_to admin_user_path(@task.user), notice: "タスクを削除しました！"
    else
      redirect_to admin_user_path(user), notice: "タスクを削除しました！"
    end
  end


  private

  def task_params
    params.require(:task).permit(:task_title, :task_content, :created_at, :deadline, :status, :priority, {label_ids: []} )
  end

  def task_search_params
    params.fetch(:search, {}).permit(:task_title, :status, :label_id )
  end

  def check_user
    @task = Task.find(params[:id])
    if current_user.id != @task.user_id
      redirect_to tasks_path, notice: '他人のページへアクセスはできません'
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only:[ :new, :create ]

  def new
    if logged_in?
      redirect_to tasks_path
    else
      @user = User.new
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash.now[:notice] = 'アカウントを作成しました！'
      session[:user_id] = @user.id
      redirect_to user_path(@user), notice: 'ログインしました！'
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
      unless @user == current_user
        redirect_to tasks_path, notice:'ログインIDとアクセスしようとしているIDが一致しません。'
      end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/labels_helper.rb
module LabelsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) 
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/edit.html.erb
<h1>【管理者画面】ユーザーの編集</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: [ :admin, @user ], local: true) do |f| %>  
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.label :admin %>
  <%= f.select :admin, [[:'管理者', :true], [:'一般ユーザー', :false]], include_blank:'選択してください'%> 

  <%= f.submit "ユーザー情報の更新" %>
<% end %>

<%= link_to '【管理者画面】の一覧へ', admin_users_path %>

app/views/admin/users/index.html.erb
<h1>【管理画面】ユーザーの一覧</h1>

<table class="table">
  <thead class="thead-light">
    <tr>
      <th scope="col">ユーザーID</th>
      <th scope="col">ユーザー名</th>
      <th scope="col">メールアドレス</th>
      <th scope="col">タスク数</th>
      <th scope="col">権限</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr class="user_table">
        <td><%= user.id %></td>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.tasks.count %></td>
        <td>
            <% if user.admin == true %>
              <a>管理者</a>
            <% else %>
              <a>一般ユーザー</a>
            <% end %>
        </td>
        <td>
          <%= link_to '詳細', admin_user_path(user), class:"btn btn-outline-primary" %>
          <%= link_to '編集', edit_admin_user_path(user), class:"btn btn-outline-success" %>
          <%= link_to '削除', admin_user_path(user), method: :delete, data:{confirm: "本当に削除して良いですか？"}, class: "btn btn-outline-danger" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'ユーザーの新規登録', new_admin_user_path, class:"btn btn-outline-success" %>
<%= link_to 'タスクの新規登録', new_user_path, class:"btn btn-outline-primary" %>

app/views/admin/users/new.html.erb
<h1>【管理者画面】ユーザーの新規登録</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: [ :admin, @user ], local: true) do |f| %>  
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.label :admin %>
  <%= f.select :admin, [[:'管理者', :true], [:'一般ユーザー', :false]], include_blank:'選択してください'%> 

  <%= f.submit "新規作成" %>
<% end %>

<%= link_to '【管理者画面】の一覧へ', admin_users_path %>

app/views/admin/users/show.html.erb
<h1><%= @user.name %>さんのタスク一覧</h1>
<p>【権限】
  <% if @user.admin == true %>
    <a>管理者</a>
  <% else %>
    <a>一般ユーザー</a>
  <% end %>
</p>

<table class="table">
  <thead class="thead-light">
    <tr>
      <th scope="col">タスク名</th>
      <th scope="col">終了期限</th>
      <th scope="col">ステータス</th>
      <th scope="col">優先順位</th>
      <th scope="col">作成者</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @user.tasks.each do |task| %>
      <tr class="task_table">
        <td><%= task.task_title %></td>
        <td><%= task.deadline %></td>
        <td><%= task.status %></td>
        <td><%= task.priority %></td>
        <td><%= task.user.name %></td>
        <td>
          <%= link_to '詳細', task_path(task), class:"btn btn-outline-primary" %>
          <%= link_to '編集', edit_task_path(task), class:"btn btn-outline-success" %>
          <%= link_to '削除', task_path(task), method: :delete, data:{confirm: "本当に削除して良いですか？"}, class: "btn btn-outline-danger" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/labels/_form.html.erb
<%= form_with(model: label, local: true) do |f| %>

  <%= f.label :label_name %>
  <%= f.text_field :label_name %>

  <%= f.submit "作成する" %> 
<% end %>

<%= link_to 'ラベルの一覧画面へ', labels_path %>

app/views/labels/index.html.erb
<h1>ラベルの一覧</h1>

<table class="table">
  <thead class="thead-light">
    <tr>
      <th scope="col">ラベル名</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% @labels.each do |label| %>
      <tr class="task_table">
        <td><%= label.label_name %></td>
        <td>
          <%= link_to '詳細', label_path(label), class:"btn btn-outline-primary" %>
          <%= link_to '編集', edit_label_path(label), class:"btn btn-outline-success" %>
          <%= link_to '削除', label_path(label), method: :delete, data:{confirm: "本当に削除して良いですか？"}, class: "btn btn-outline-danger" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<p><%= link_to 'ラベルの新規作成', labels_path %></p>
<p><%= link_to 'タスクの一覧へ戻る', tasks_path %></p>

app/views/labels/new.html.erb
<h1>ラベルの新規作成</h1>

<%= render 'form', label:@label %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>

    <% if logged_in? %>
      <%= link_to 'Profile', user_path(current_user.id) %>
      <%= link_to 'Logout', session_path(current_user.id), method: :delete %>
    <% else %>
      <%= link_to 'Sing up', new_user_path %>
      <%= link_to 'Login', new_session_path %>
    <% end %>

    <%= yield %>

    <!-- ここから -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <!-- ここまで -->
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |f| %>

  <% if task.errors.any? %>
    <div class="error_explanation">
      <h2><%= task.errors.count %>件のエラーがあります。</h2>
      <ul>
        <% task.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-group">
    <div class="input-group-prepend">
      <span class="input-group-text"><%= f.label :task_title %></span>
      <%= f.text_field :task_title %>
    </div>
  </div>
  <div class="input-group">
    <div class="input-group-prepend">
      <span class="input-group-text"><%= f.label :task_content %></span>
      <%= f.text_area :task_content %>
    </div>
  </div>
  <div class="input-group">
    <div class="input-group-prepend">
      <span class="input-group-text"><%= f.label :deadline %></span>
      <%= f.date_select :deadline,:date_separator => " - " %>
    </div>
  </div>
  <div class="input-group">
    <div class="input-group-prepend">
      <span class="input-group-text"><%= f.label :status %></span>
      <%= f.select :status, Task.statuses.keys.to_a, include_blank:'選択してください'%>
    </div>
  </div>
  <div class="input-group">
    <div class="input-group-prepend">
      <span class="input-group-text"><%= f.label :priority %></span>
      <%= f.select :priority, Task.priorities.keys.to_a, include_blank:'選択してください'%>
    </div>
  </div>
  <div class="input-group">
    <div class="input-group-prepend">
      <span class="input-group-text">タスクラベル</span>
      <%= f.collection_check_boxes(:label_ids, Label.all, :id, :label_name) %>
    </div>
  </div>

  <br>
  
  <%= f.submit "作成する" %> 
<% end %>

app/views/tasks/edit.html.erb
<h1 class="display-4">タスクの編集</h1>

<%= render 'form', task: @task %>

app/views/tasks/index.html.erb
<h1 class="display-4">タスクの一覧</h1>

<p><%= notice %></p>

<div class="serch-form">
  <%= form_with(scope: :search, url:tasks_path, method: :get, local: true) do |f| %>
    <%= f.label :task_title %>
    <%= f.text_field :task_title, value: @search_params[:task_title] %>
    <%= f.label :status %>
    <%= f.select :status, Task.statuses.keys.to_a , include_blank:'選択してください' ,value: @search_params[:status] %>
    <%= f.label :label_name %>
    <%= f.select :label_id, Label.pluck(:label_name, :id), { include_blank: '選択してください'},value: @search_params[:label_id] %>
    <%= f.submit "検索"%> 
  <% end %>
</div>

<table class="table">
  <thead class="thead-light">
    <tr>
      <th scope="col">タスク名</th>
      <th scope="col">終了期限</th>
      <th scope="col">ステータス</th>
      <th scope="col">優先順位</th>
      <th scope="col">作成者</th>
      <th scope="col">ラベル</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr class="task_table">
        <td><%= task.task_title %></td>
        <td><%= task.deadline %></td>
        <td><%= task.status %></td>
        <td><%= task.priority %></td>
        <td><%= task.user.name %></td>
        <td>
          <% task.labels.each do |label| %>
            <%= label.label_name %><a>/</a>
          <% end %> 
        </td>
        <td> 
          <%= link_to '詳細', task_path(task), class:"btn btn-outline-primary" %>
          <%= link_to '編集', edit_task_path(task), class:"btn btn-outline-success" %>
          <%= link_to '削除', task_path(task), method: :delete, data:{confirm: "本当に削除して良いですか？"}, class: "btn btn-outline-danger" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @tasks %>

<p><%= link_to 'タスクの新規投稿', new_task_path %></p>

<p><%= link_to "終了期限でソートする", tasks_path(sort_expired: "true") %></p>
<p><%= link_to "優先順位でソートする", tasks_path(sort_priority: "true") %></p>

app/views/tasks/new.html.erb
<h1 class="display-4">タスクの新規作成</h1>

<%= render 'form', task: @task %>

app/views/tasks/show.html.erb
<h1 class="display-4">タスクの詳細</h1>
<p><%= notice %></p>

<p>タスク名：<%= @task.task_title %></p>
<p>タスク内容：<%= @task.task_content %></p>
<p>終了期限：<%= @task.deadline %></p>
<p>ステータス：<%= @task.status %></p>
<p>優先順位：<%= @task.priority %></p>
<p>作成者：<%= @task.user.name %></p>
<p>ラベル名：
  <% @task.labels.each do |label| %>
    <%= label.label_name %><a>/</a>
  <% end %>
</p>


<%= link_to '戻る', tasks_path %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>  
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit "新規登録" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>

<p>メールアドレス: <%= @user.email %></p>

<p><%= link_to 'タスクの新規登録', new_task_path %></p>
<p><%= link_to 'タスク一覧に戻る', tasks_path %></p>

<% if current_user.admin == true %>
  <%= link_to '管理者画面へ', admin_users_path %>
  <%= link_to 'ラベル作成画面へ', new_label_path %>
<% end %>